runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  NODE_ENV: "production"
  MONGO_URI: "mongodb+srv://pramana_ai:9441166030@Nk@cluster0.p4tbwui.mongodb.net/jobportal?retryWrites=true&w=majority"
